### ISSUE TITLE
Erro no final

### ISSUE THREAD

**Issue by Knzaa** [katomaro/PechinchAli_Bot#1]
Boa tarde!
Primeiramente, muito obrigado por disponibilizar o bot, genial essa ideia.
Mas quando a minha pechincha chegou em 98,50% o aliexpress me bloqueou, eu segui os passos para colocar o proxy e o devicelist, mas acabou não dando certo. No caso do meu produto eu precisaria de 1600 ajudas, então eu teria que colocar uma lista com essa quantidade de proxy/device? Outra coisa, tem algum problema abrir mais de um cmd, e deixar o bot rodando em 10 abas por exemplo, para que seja mais rápido?
Vlww d+, amigo.

**Comment by katomaro** [comment]
Obrigado por entrar em contato @Knzaa.
Na realidade a Ali bloqueia o pedido **antes** de chegar nessa % e só revela quando chega nela. Não sei a regra exata de bloqueio (tipo, X contas fake identificadas).
### Sobre a quantidade...
A **lista de dispositivos**, para adicionar mais você teria que [mudar a configuração do seu navegador](https://developer.chrome.com/docs/devtools/device-mode/), mas não é muito necessário rotacionar em mil dispositivos por exemplo.  

Já na **lista de proxies**, quanto mais proxies você adicionar, melhor, lembre que o bot escolhe um da lista aleatoriamente, não tem controle sobre repetidos nessa versão (anotei isso agora para implementar na próxima update que vou adicionar GUI, concorrência e links simultâneos) então pode ser que _ele escolha o mesmo proxy várias vezes consecutivas_, o que de fato prejudicaria, uma chance pequena, mas possível. Outro ponto que devo levantar **são os números**, esse evento está popular agora e tem bastante gente correndo atrás, falando do meu bot em específico, no momento dessa resposta ele tem **22 clones, 1 fork e 748 visualizações** aqui no github, apenas 127 visualizações tem referer do YouTube, e por falar nele, o vídeo onde faço o passo-a-passo do bot está com 511 visualizações nesse momento, ainda antes disso por ~2 dias eu deixei ele em grupos pelo Google Drive. Isso apenas o meu, talvez seja justo dizer que pelo menos ~500 pessoas estão usando (desconsiderando caso de amigo passar entre si diretamente), e ressalto que o meu bot **não é o único** (e ainda assim, falando apenas dos públicos) e também tem pessoas usando macros. Onde eu quero chegar é que por mais que você monte uma lista gigante de proxies, tem uma chance alta de que tem mais gente usando aqueles IPs para a mesma finalidade, fazendo com que a Ali marque-os temporariamente como bot, assim causando bloqueios em Pechinchas.**O que eu recomendo no momento é ir atrás de comprar listas de proxies, mais seguro não ser bloqueado, mas saiba que o pessoal vai desanimando da promoção eventualmente e vai tudo voltar a funcionar conforme o tempo passar**, veja como um investimento, se você revende os produtos, as listas se pagam (não tenho nenhuma para recomendar infelizmente).
### Sobre múltiplas instâncias (abrir vários cmds)....
Pode fazer isso tranquilamente, só lembro que eles vão estar usando a mesma lista de proxies o que pode fazer com que sejam selecionados e enviados ajudas dos mesmos de forma frequente. Bom ter uma lista gigante para poder fazer isso tranquilamente. O que recomendo é ter pelo menos ~40-60% das ajudas necessárias em proxies. (+~20% por cmd com fim de evitar repetidos).
### TLDR
Proxy público/baratinho tá difícil de usar atualmente.

#### Em adendo:
Quando a ali bloqueia uma Pechincha daquela conta, as outras ficam mais difíceis de serem concluídas, como se você estivesse pagando pelo seu pecado.

**Comment by Knzaa** [comment]
Muito obrigado pela resposta e pelas dicas também, vlwww d+ :)
